config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :campaigns
  resources :users

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'campaigns#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCRYPT::Enging.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.all
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(campaign_params)
    p ">>>>>>>>>>>>>>>>>>>>>>", campaign_params, ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    @campaign.save
  end

  private
    def campaign_params
      params.require(:campaign).permit(:title, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # log that beyotch in
      log_in user
      redirect_to user
    else
      #invalid creds or user does not exist
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before :user_params, except: 'create'

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = "Account successfully created! Welcome to Armory!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for (user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/campaigns/index.html.erb
<div class="page-header">
  <span><h2>Campaigns</h2></span>
  <hr>
  <span><%= link_to "New", new_campaign_path %></span>
</div>



<% @campaigns.each do |camp| %>
  <h3> <%= link_to camp.title, campaign_path(camp.id) %> </h3>
  <p> <%= camp.description %> </p>
  <hr>
<% end %>

app/views/campaigns/new.html.erb
<h2>New Campaign</h2>

<%= form_for @campaign do |f| %>
  <p>
    <%= f.label(:title) %>
    <%= f.text_field(:title) %>
  </p>
  <p>
    <%= f.label(:description) %>
    <%= f.text_area(:description) %>
  </p>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/show.html.erb
<h2><%= @campaign.title %></h2>


<p><%= @campaign.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Armory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Armory", campaigns_path, class:"navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse">

          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to "Users", "#" %></li>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Log Out", logout_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log In", login_path %></li>
              <li><%= link_to "Sign Up", signup_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>



    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"> <%= message %> </div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'shared/error_messages' %>
    <%= form_for @user do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirm, 'Confirmation' %>
      <%= f.password_field :password_confirm, class: 'form-control' %>

      <%= f.submit 'Create Account', class: 'btn btn-primary' %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>

<%= @user.email %>